// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13_vRM-bclMNyrRcSOx9lbRC2J3rWnVY',
    appId: '1:840562757917:web:109d611272ffac4e7a51f4',
    messagingSenderId: '840562757917',
    projectId: 'ecocycle-71a0b',
    authDomain: 'ecocycle-71a0b.firebaseapp.com',
    storageBucket: 'ecocycle-71a0b.appspot.com',
    measurementId: 'G-VR61ZRL1BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYJlnCvXNykpFR5SUKqMvQmCCWtHNRiQ',
    appId: '1:840562757917:android:00122f0e2bb022287a51f4',
    messagingSenderId: '840562757917',
    projectId: 'ecocycle-71a0b',
    storageBucket: 'ecocycle-71a0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWiLuDuQXaVWj8nFD_-IpC3sNxleMaJS0',
    appId: '1:840562757917:ios:1ef0a1abc5ffda3a7a51f4',
    messagingSenderId: '840562757917',
    projectId: 'ecocycle-71a0b',
    storageBucket: 'ecocycle-71a0b.appspot.com',
    iosBundleId: 'com.example.ecocycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWiLuDuQXaVWj8nFD_-IpC3sNxleMaJS0',
    appId: '1:840562757917:ios:1ef0a1abc5ffda3a7a51f4',
    messagingSenderId: '840562757917',
    projectId: 'ecocycle-71a0b',
    storageBucket: 'ecocycle-71a0b.appspot.com',
    iosBundleId: 'com.example.ecocycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC13_vRM-bclMNyrRcSOx9lbRC2J3rWnVY',
    appId: '1:840562757917:web:382b7751deb07f177a51f4',
    messagingSenderId: '840562757917',
    projectId: 'ecocycle-71a0b',
    authDomain: 'ecocycle-71a0b.firebaseapp.com',
    storageBucket: 'ecocycle-71a0b.appspot.com',
    measurementId: 'G-DK94VN259C',
  );
}
